
package gov.nih.nlm.uts.webservice.security;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtsWsSecurityController", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtsWsSecurityController {


    /**
     * 
     * @param pw
     * @param user
     * @return
     *     returns java.lang.String
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProxyGrantTicket", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.security.GetProxyGrantTicket")
    @ResponseWrapper(localName = "getProxyGrantTicketResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.security.GetProxyGrantTicketResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/getProxyGrantTicketRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/getProxyGrantTicketResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/getProxyGrantTicket/Fault/UtsFault")
    })
    public String getProxyGrantTicket(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pw", targetNamespace = "")
        String pw)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param apikey
     * @return
     *     returns java.lang.String
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProxyGrantTicketWithApiKey", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.security.GetProxyGrantTicketWithApiKey")
    @ResponseWrapper(localName = "getProxyGrantTicketWithApiKeyResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.security.GetProxyGrantTicketWithApiKeyResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/getProxyGrantTicketWithApiKeyRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/getProxyGrantTicketWithApiKeyResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/getProxyGrantTicketWithApiKey/Fault/UtsFault")
    })
    public String getProxyGrantTicketWithApiKey(
        @WebParam(name = "apikey", targetNamespace = "")
        String apikey)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param tgt
     * @param service
     * @return
     *     returns java.lang.String
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProxyTicket", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.security.GetProxyTicket")
    @ResponseWrapper(localName = "getProxyTicketResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.security.GetProxyTicketResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/getProxyTicketRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/getProxyTicketResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/getProxyTicket/Fault/UtsFault")
    })
    public String getProxyTicket(
        @WebParam(name = "TGT", targetNamespace = "")
        String tgt,
        @WebParam(name = "service", targetNamespace = "")
        String service)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param service
     * @return
     *     returns java.lang.String
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateProxyTicket", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.security.ValidateProxyTicket")
    @ResponseWrapper(localName = "validateProxyTicketResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.security.ValidateProxyTicketResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/validateProxyTicketRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/validateProxyTicketResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsSecurityController/validateProxyTicket/Fault/UtsFault")
    })
    public String validateProxyTicket(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "service", targetNamespace = "")
        String service)
        throws UtsFault_Exception
    ;

}
