
package gov.nih.nlm.uts.webservice.finder;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtsWsFinderController", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtsWsFinderController {


    /**
     * 
     * @param psf
     * @param ticket
     * @param string
     * @param searchType
     * @param version
     * @param returnType
     * @param target
     * @return
     *     returns int
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCount", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.GetCount")
    @ResponseWrapper(localName = "getCountResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.GetCountResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/getCountRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/getCountResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/getCount/Fault/UtsFault")
    })
    public int getCount(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "returnType", targetNamespace = "")
        String returnType,
        @WebParam(name = "target", targetNamespace = "")
        String target,
        @WebParam(name = "string", targetNamespace = "")
        String string,
        @WebParam(name = "searchType", targetNamespace = "")
        String searchType,
        @WebParam(name = "psf", targetNamespace = "")
        Psf psf)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param psf
     * @param ticket
     * @param string
     * @param searchType
     * @param version
     * @param target
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.finder.UiLabel>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAtoms", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.FindAtoms")
    @ResponseWrapper(localName = "findAtomsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.FindAtomsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findAtomsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findAtomsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findAtoms/Fault/UtsFault")
    })
    public List<UiLabel> findAtoms(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "target", targetNamespace = "")
        String target,
        @WebParam(name = "string", targetNamespace = "")
        String string,
        @WebParam(name = "searchType", targetNamespace = "")
        String searchType,
        @WebParam(name = "psf", targetNamespace = "")
        Psf psf)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param psf
     * @param ticket
     * @param string
     * @param searchType
     * @param version
     * @param target
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.finder.UiLabel>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findConcepts", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.FindConcepts")
    @ResponseWrapper(localName = "findConceptsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.FindConceptsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findConceptsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findConceptsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findConcepts/Fault/UtsFault")
    })
    public List<UiLabel> findConcepts(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "target", targetNamespace = "")
        String target,
        @WebParam(name = "string", targetNamespace = "")
        String string,
        @WebParam(name = "searchType", targetNamespace = "")
        String searchType,
        @WebParam(name = "psf", targetNamespace = "")
        Psf psf)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param psf
     * @param ticket
     * @param string
     * @param searchType
     * @param version
     * @param target
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.finder.UiLabelRootSource>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCodes", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.FindCodes")
    @ResponseWrapper(localName = "findCodesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.FindCodesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findCodesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findCodesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findCodes/Fault/UtsFault")
    })
    public List<UiLabelRootSource> findCodes(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "target", targetNamespace = "")
        String target,
        @WebParam(name = "string", targetNamespace = "")
        String string,
        @WebParam(name = "searchType", targetNamespace = "")
        String searchType,
        @WebParam(name = "psf", targetNamespace = "")
        Psf psf)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param psf
     * @param ticket
     * @param string
     * @param searchType
     * @param version
     * @param target
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.finder.UiLabelRootSource>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findSourceConcepts", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.FindSourceConcepts")
    @ResponseWrapper(localName = "findSourceConceptsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.FindSourceConceptsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findSourceConceptsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findSourceConceptsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findSourceConcepts/Fault/UtsFault")
    })
    public List<UiLabelRootSource> findSourceConcepts(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "target", targetNamespace = "")
        String target,
        @WebParam(name = "string", targetNamespace = "")
        String string,
        @WebParam(name = "searchType", targetNamespace = "")
        String searchType,
        @WebParam(name = "psf", targetNamespace = "")
        Psf psf)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param psf
     * @param ticket
     * @param string
     * @param searchType
     * @param version
     * @param target
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.finder.UiLabelRootSource>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findSourceDescriptors", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.FindSourceDescriptors")
    @ResponseWrapper(localName = "findSourceDescriptorsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.finder.FindSourceDescriptorsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findSourceDescriptorsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findSourceDescriptorsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsFinderController/findSourceDescriptors/Fault/UtsFault")
    })
    public List<UiLabelRootSource> findSourceDescriptors(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "target", targetNamespace = "")
        String target,
        @WebParam(name = "string", targetNamespace = "")
        String string,
        @WebParam(name = "searchType", targetNamespace = "")
        String searchType,
        @WebParam(name = "psf", targetNamespace = "")
        Psf psf)
        throws UtsFault_Exception
    ;

}
