
package gov.nih.nlm.uts.webservice.metadata;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtsWsMetadataController", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtsWsMetadataController {


    /**
     * 
     * @param ticket
     * @param version
     * @param versionedSourceAbbreviation
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.SourceDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSource", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSource")
    @ResponseWrapper(localName = "getSourceResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSource/Fault/UtsFault")
    })
    public SourceDTO getSource(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "versionedSourceAbbreviation", targetNamespace = "")
        String versionedSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param attributeName
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.AttributeNameDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttributeName", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAttributeName")
    @ResponseWrapper(localName = "getAttributeNameResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAttributeNameResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAttributeNameRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAttributeNameResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAttributeName/Fault/UtsFault")
    })
    public AttributeNameDTO getAttributeName(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "attributeName", targetNamespace = "")
        String attributeName)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @return
     *     returns java.lang.String
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentUMLSVersion", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetCurrentUMLSVersion")
    @ResponseWrapper(localName = "getCurrentUMLSVersionResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetCurrentUMLSVersionResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCurrentUMLSVersionRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCurrentUMLSVersionResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCurrentUMLSVersion/Fault/UtsFault")
    })
    public String getCurrentUMLSVersion(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @return
     *     returns java.lang.String
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUMLSVersions", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllUMLSVersions")
    @ResponseWrapper(localName = "getAllUMLSVersionsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllUMLSVersionsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllUMLSVersionsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllUMLSVersionsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllUMLSVersions/Fault/UtsFault")
    })
    public String getAllUMLSVersions(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.ContactInformationDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAcquisitionContactInformation", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAcquisitionContactInformation")
    @ResponseWrapper(localName = "getAcquisitionContactInformationResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAcquisitionContactInformationResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAcquisitionContactInformationRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAcquisitionContactInformationResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAcquisitionContactInformation/Fault/UtsFault")
    })
    public ContactInformationDTO getAcquisitionContactInformation(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @param additionalRelationLabel
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.AdditionalRelationLabelDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdditionalRelationLabel", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAdditionalRelationLabel")
    @ResponseWrapper(localName = "getAdditionalRelationLabelResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAdditionalRelationLabelResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAdditionalRelationLabelRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAdditionalRelationLabelResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAdditionalRelationLabel/Fault/UtsFault")
    })
    public AdditionalRelationLabelDTO getAdditionalRelationLabel(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "additionalRelationLabel", targetNamespace = "")
        String additionalRelationLabel)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param characterSet
     * @param ticket
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.CharacterSetDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCharacterSet", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetCharacterSet")
    @ResponseWrapper(localName = "getCharacterSetResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetCharacterSetResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCharacterSetRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCharacterSetResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCharacterSet/Fault/UtsFault")
    })
    public CharacterSetDTO getCharacterSet(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "characterSet", targetNamespace = "")
        String characterSet)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.ContactInformationDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContentContactInformation", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetContentContactInformation")
    @ResponseWrapper(localName = "getContentContactInformationResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetContentContactInformationResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getContentContactInformationRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getContentContactInformationResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getContentContactInformation/Fault/UtsFault")
    })
    public ContactInformationDTO getContentContactInformation(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param cooccurrenceType
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.CooccurrenceTypeDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCooccurrenceType", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetCooccurrenceType")
    @ResponseWrapper(localName = "getCooccurrenceTypeResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetCooccurrenceTypeResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCooccurrenceTypeRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCooccurrenceTypeResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCooccurrenceType/Fault/UtsFault")
    })
    public CooccurrenceTypeDTO getCooccurrenceType(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "cooccurrenceType", targetNamespace = "")
        String cooccurrenceType)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.SourceDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentVersionSource", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetCurrentVersionSource")
    @ResponseWrapper(localName = "getCurrentVersionSourceResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetCurrentVersionSourceResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCurrentVersionSourceRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCurrentVersionSourceResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getCurrentVersionSource/Fault/UtsFault")
    })
    public SourceDTO getCurrentVersionSource(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param generalMetadata
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.GeneralMetadataEntryDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGeneralMetadataEntry", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetGeneralMetadataEntry")
    @ResponseWrapper(localName = "getGeneralMetadataEntryResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetGeneralMetadataEntryResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getGeneralMetadataEntryRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getGeneralMetadataEntryResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getGeneralMetadataEntry/Fault/UtsFault")
    })
    public List<GeneralMetadataEntryDTO> getGeneralMetadataEntry(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "generalMetadata", targetNamespace = "")
        String generalMetadata)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param identifier
     * @param ticket
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.IdentifierTypeDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIdentifierType", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetIdentifierType")
    @ResponseWrapper(localName = "getIdentifierTypeResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetIdentifierTypeResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getIdentifierTypeRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getIdentifierTypeResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getIdentifierType/Fault/UtsFault")
    })
    public IdentifierTypeDTO getIdentifierType(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "identifier", targetNamespace = "")
        String identifier)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.ContactInformationDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLicenseContactInformation", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetLicenseContactInformation")
    @ResponseWrapper(localName = "getLicenseContactInformationResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetLicenseContactInformationResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getLicenseContactInformationRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getLicenseContactInformationResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getLicenseContactInformation/Fault/UtsFault")
    })
    public ContactInformationDTO getLicenseContactInformation(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param relationLabel
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.RelationLabelDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRelationLabel", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRelationLabel")
    @ResponseWrapper(localName = "getRelationLabelResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRelationLabelResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRelationLabelRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRelationLabelResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRelationLabel/Fault/UtsFault")
    })
    public RelationLabelDTO getRelationLabel(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "relationLabel", targetNamespace = "")
        String relationLabel)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.RootSourceDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRootSource", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRootSource")
    @ResponseWrapper(localName = "getRootSourceResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRootSourceResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourceRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourceResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSource/Fault/UtsFault")
    })
    public RootSourceDTO getRootSource(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRootSourceSynonymousNames", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRootSourceSynonymousNames")
    @ResponseWrapper(localName = "getRootSourceSynonymousNamesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRootSourceSynonymousNamesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourceSynonymousNamesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourceSynonymousNamesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourceSynonymousNames/Fault/UtsFault")
    })
    public List<String> getRootSourceSynonymousNames(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param attributeName
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.SourceAttributeNameDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSourceAttributeName", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceAttributeName")
    @ResponseWrapper(localName = "getSourceAttributeNameResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceAttributeNameResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceAttributeNameRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceAttributeNameResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceAttributeName/Fault/UtsFault")
    })
    public SourceAttributeNameDTO getSourceAttributeName(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation,
        @WebParam(name = "attributeName", targetNamespace = "")
        String attributeName)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceAttributeNameDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSourceAttributeNames", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceAttributeNames")
    @ResponseWrapper(localName = "getSourceAttributeNamesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceAttributeNamesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceAttributeNamesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceAttributeNamesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceAttributeNames/Fault/UtsFault")
    })
    public List<SourceAttributeNameDTO> getSourceAttributeNames(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param citation
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.SourceCitationDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSourceCitation", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceCitation")
    @ResponseWrapper(localName = "getSourceCitationResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceCitationResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceCitationRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceCitationResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceCitation/Fault/UtsFault")
    })
    public SourceCitationDTO getSourceCitation(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "citation", targetNamespace = "")
        String citation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param relationLabel
     * @param rootSourceAbbreviation
     * @param version
     * @param additionalRelationLabel
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.SourceRelationLabelDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSourceRelationLabel", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceRelationLabel")
    @ResponseWrapper(localName = "getSourceRelationLabelResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceRelationLabelResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceRelationLabelRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceRelationLabelResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceRelationLabel/Fault/UtsFault")
    })
    public SourceRelationLabelDTO getSourceRelationLabel(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation,
        @WebParam(name = "relationLabel", targetNamespace = "")
        String relationLabel,
        @WebParam(name = "additionalRelationLabel", targetNamespace = "")
        String additionalRelationLabel)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceRelationLabelDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSourceRelationLabels", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceRelationLabels")
    @ResponseWrapper(localName = "getSourceRelationLabelsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceRelationLabelsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceRelationLabelsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceRelationLabelsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceRelationLabels/Fault/UtsFault")
    })
    public List<SourceRelationLabelDTO> getSourceRelationLabels(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param termType
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.SourceTermTypeDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSourceTermType", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceTermType")
    @ResponseWrapper(localName = "getSourceTermTypeResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceTermTypeResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceTermTypeRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceTermTypeResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceTermType/Fault/UtsFault")
    })
    public SourceTermTypeDTO getSourceTermType(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation,
        @WebParam(name = "termType", targetNamespace = "")
        String termType)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceTermTypeDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSourceTermTypes", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceTermTypes")
    @ResponseWrapper(localName = "getSourceTermTypesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSourceTermTypesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceTermTypesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceTermTypesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSourceTermTypes/Fault/UtsFault")
    })
    public List<SourceTermTypeDTO> getSourceTermTypes(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param atn
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceAttributeNameDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubEquivalentAttributeNames", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSubEquivalentAttributeNames")
    @ResponseWrapper(localName = "getSubEquivalentAttributeNamesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSubEquivalentAttributeNamesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSubEquivalentAttributeNamesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSubEquivalentAttributeNamesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSubEquivalentAttributeNames/Fault/UtsFault")
    })
    public List<SourceAttributeNameDTO> getSubEquivalentAttributeNames(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "atn", targetNamespace = "")
        String atn,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param subHeading
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.SubheadingDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubheading", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSubheading")
    @ResponseWrapper(localName = "getSubheadingResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetSubheadingResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSubheadingRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSubheadingResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getSubheading/Fault/UtsFault")
    })
    public SubheadingDTO getSubheading(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "subHeading", targetNamespace = "")
        String subHeading)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param termType
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.TermTypeDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTermType", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetTermType")
    @ResponseWrapper(localName = "getTermTypeResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetTermTypeResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getTermTypeRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getTermTypeResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getTermType/Fault/UtsFault")
    })
    public TermTypeDTO getTermType(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "termType", targetNamespace = "")
        String termType)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.AdditionalRelationLabelDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAdditionalRelationLabels", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllAdditionalRelationLabels")
    @ResponseWrapper(localName = "getAllAdditionalRelationLabelsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllAdditionalRelationLabelsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllAdditionalRelationLabelsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllAdditionalRelationLabelsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllAdditionalRelationLabels/Fault/UtsFault")
    })
    public List<AdditionalRelationLabelDTO> getAllAdditionalRelationLabels(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.AttributeNameDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAttributeNames", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllAttributeNames")
    @ResponseWrapper(localName = "getAllAttributeNamesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllAttributeNamesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllAttributeNamesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllAttributeNamesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllAttributeNames/Fault/UtsFault")
    })
    public List<AttributeNameDTO> getAllAttributeNames(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.CharacterSetDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCharacterSets", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllCharacterSets")
    @ResponseWrapper(localName = "getAllCharacterSetsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllCharacterSetsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllCharacterSetsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllCharacterSetsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllCharacterSets/Fault/UtsFault")
    })
    public List<CharacterSetDTO> getAllCharacterSets(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.CooccurrenceTypeDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCooccurrenceTypes", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllCooccurrenceTypes")
    @ResponseWrapper(localName = "getAllCooccurrenceTypesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllCooccurrenceTypesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllCooccurrenceTypesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllCooccurrenceTypesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllCooccurrenceTypes/Fault/UtsFault")
    })
    public List<CooccurrenceTypeDTO> getAllCooccurrenceTypes(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param atn
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceAttributeNameDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEquivalentAttributeNames", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllEquivalentAttributeNames")
    @ResponseWrapper(localName = "getAllEquivalentAttributeNamesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllEquivalentAttributeNamesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllEquivalentAttributeNamesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllEquivalentAttributeNamesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllEquivalentAttributeNames/Fault/UtsFault")
    })
    public List<SourceAttributeNameDTO> getAllEquivalentAttributeNames(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "atn", targetNamespace = "")
        String atn,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.LanguageDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLanguages", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllLanguages")
    @ResponseWrapper(localName = "getAllLanguagesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllLanguagesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllLanguagesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllLanguagesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllLanguages/Fault/UtsFault")
    })
    public List<LanguageDTO> getAllLanguages(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.RelationLabelDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRelationLabels", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllRelationLabels")
    @ResponseWrapper(localName = "getAllRelationLabelsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllRelationLabelsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllRelationLabelsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllRelationLabelsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllRelationLabels/Fault/UtsFault")
    })
    public List<RelationLabelDTO> getAllRelationLabels(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param languageAbbreviation
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.RootSourceDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRootSourcesByLanguage", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRootSourcesByLanguage")
    @ResponseWrapper(localName = "getRootSourcesByLanguageResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRootSourcesByLanguageResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourcesByLanguageRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourcesByLanguageResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourcesByLanguage/Fault/UtsFault")
    })
    public List<RootSourceDTO> getRootSourcesByLanguage(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "languageAbbreviation", targetNamespace = "")
        String languageAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param restrictionLevel
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.RootSourceDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRootSourcesByRestrictionLevel", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRootSourcesByRestrictionLevel")
    @ResponseWrapper(localName = "getRootSourcesByRestrictionLevelResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRootSourcesByRestrictionLevelResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourcesByRestrictionLevelRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourcesByRestrictionLevelResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourcesByRestrictionLevel/Fault/UtsFault")
    })
    public List<RootSourceDTO> getRootSourcesByRestrictionLevel(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "restrictionLevel", targetNamespace = "")
        int restrictionLevel)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.RootSourceDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRootSources", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllRootSources")
    @ResponseWrapper(localName = "getAllRootSourcesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllRootSourcesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllRootSourcesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllRootSourcesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllRootSources/Fault/UtsFault")
    })
    public List<RootSourceDTO> getAllRootSources(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceAttributeNameDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSourceAttributeNames", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSourceAttributeNames")
    @ResponseWrapper(localName = "getAllSourceAttributeNamesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSourceAttributeNamesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceAttributeNamesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceAttributeNamesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceAttributeNames/Fault/UtsFault")
    })
    public List<SourceAttributeNameDTO> getAllSourceAttributeNames(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceCitationDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSourceCitations", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSourceCitations")
    @ResponseWrapper(localName = "getAllSourceCitationsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSourceCitationsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceCitationsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceCitationsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceCitations/Fault/UtsFault")
    })
    public List<SourceCitationDTO> getAllSourceCitations(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceRelationLabelDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSourceRelationLabels", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSourceRelationLabels")
    @ResponseWrapper(localName = "getAllSourceRelationLabelsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSourceRelationLabelsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceRelationLabelsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceRelationLabelsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceRelationLabels/Fault/UtsFault")
    })
    public List<SourceRelationLabelDTO> getAllSourceRelationLabels(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSources", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSources")
    @ResponseWrapper(localName = "getAllSourcesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSourcesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourcesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourcesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSources/Fault/UtsFault")
    })
    public List<SourceDTO> getAllSources(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceTermTypeDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSourceTermTypes", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSourceTermTypes")
    @ResponseWrapper(localName = "getAllSourceTermTypesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSourceTermTypesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceTermTypesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceTermTypesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSourceTermTypes/Fault/UtsFault")
    })
    public List<SourceTermTypeDTO> getAllSourceTermTypes(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SubheadingDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSubheadings", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSubheadings")
    @ResponseWrapper(localName = "getAllSubheadingsResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSubheadingsResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSubheadingsRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSubheadingsResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSubheadings/Fault/UtsFault")
    })
    public List<SubheadingDTO> getAllSubheadings(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param atn
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceAttributeNameDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSuperAttributeNames", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSuperAttributeNames")
    @ResponseWrapper(localName = "getAllSuperAttributeNamesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllSuperAttributeNamesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSuperAttributeNamesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSuperAttributeNamesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllSuperAttributeNames/Fault/UtsFault")
    })
    public List<SourceAttributeNameDTO> getAllSuperAttributeNames(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "atn", targetNamespace = "")
        String atn,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.TermTypeDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllTermTypes", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllTermTypes")
    @ResponseWrapper(localName = "getAllTermTypesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllTermTypesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllTermTypesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllTermTypesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllTermTypes/Fault/UtsFault")
    })
    public List<TermTypeDTO> getAllTermTypes(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param rootSourceAbbreviation
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVersionedSources", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetVersionedSources")
    @ResponseWrapper(localName = "getVersionedSourcesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetVersionedSourcesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getVersionedSourcesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getVersionedSourcesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getVersionedSources/Fault/UtsFault")
    })
    public List<SourceDTO> getVersionedSources(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "rootSourceAbbreviation", targetNamespace = "")
        String rootSourceAbbreviation)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.SourceDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUpdatedSourcesByVersion", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetUpdatedSourcesByVersion")
    @ResponseWrapper(localName = "getUpdatedSourcesByVersionResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetUpdatedSourcesByVersionResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getUpdatedSourcesByVersionRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getUpdatedSourcesByVersionResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getUpdatedSourcesByVersion/Fault/UtsFault")
    })
    public List<SourceDTO> getUpdatedSourcesByVersion(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param family
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.RootSourceDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRootSourcesByFamily", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRootSourcesByFamily")
    @ResponseWrapper(localName = "getRootSourcesByFamilyResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetRootSourcesByFamilyResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourcesByFamilyRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourcesByFamilyResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getRootSourcesByFamily/Fault/UtsFault")
    })
    public List<RootSourceDTO> getRootSourcesByFamily(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "family", targetNamespace = "")
        String family)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param version
     * @return
     *     returns java.util.List<gov.nih.nlm.uts.webservice.metadata.RootSourceDTO>
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRootSourceFamilies", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllRootSourceFamilies")
    @ResponseWrapper(localName = "getAllRootSourceFamiliesResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetAllRootSourceFamiliesResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllRootSourceFamiliesRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllRootSourceFamiliesResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getAllRootSourceFamilies/Fault/UtsFault")
    })
    public List<RootSourceDTO> getAllRootSourceFamilies(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version)
        throws UtsFault_Exception
    ;

    /**
     * 
     * @param ticket
     * @param language
     * @param version
     * @return
     *     returns gov.nih.nlm.uts.webservice.metadata.LanguageDTO
     * @throws UtsFault_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLanguage", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetLanguage")
    @ResponseWrapper(localName = "getLanguageResponse", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", className = "gov.nih.nlm.uts.webservice.metadata.GetLanguageResponse")
    @Action(input = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getLanguageRequest", output = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getLanguageResponse", fault = {
        @FaultAction(className = UtsFault_Exception.class, value = "http://webservice.uts.umls.nlm.nih.gov/UtsWsMetadataController/getLanguage/Fault/UtsFault")
    })
    public LanguageDTO getLanguage(
        @WebParam(name = "ticket", targetNamespace = "")
        String ticket,
        @WebParam(name = "version", targetNamespace = "")
        String version,
        @WebParam(name = "language", targetNamespace = "")
        String language)
        throws UtsFault_Exception
    ;

}
